[book]
title = "Kubernetes Attack Workshop"
author = "Appsecco and Praetorian"
description = "Praetorian + Appsecco training course content on Attacking and Auditing Dockers Containers and Kubernetes Clusters"
language = "en"
multilingual = false
src = "src"
