# https://www.mickaelvieira.com/blog/2020/01/29/deploying-a-static-website-to-google-cloud-storage-with-github-actions.html

name: Website - Production # name of your workflow
on:
  push:
    branches:
      - master # Deployment will be triggered when we will push to the master branch
jobs:
  build:
    name: Build & Deploy # name of the job
    runs-on: ubuntu-latest # the runner in which the job will be executed
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        fetch-depth: 1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '276.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: gsutil -m rsync -d -c -r mdbook/book gs://www.planetkesten.com/k8s-workbook/
    - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://www.planetkesten.com/**/*.html
    - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://www.planetkesten.com/**/*.js
    - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://www.planetkesten.com/**/*.css

